C++ = g++
COPS = -Wall -std=c++11

make: task1a task1b

clean:
	rm task1a task1b 

cleanwin:
	del *.exe *.o

task1a:
	$(C++) $(COPS) -o task1a task1a.cpp stopwatch.cpp 

task1b:
	$(C++) $(COPS) -o task1b task1b.cpp stopwatch.cpp 
