CC = gcc
COPS = -Wall

make: task1 task2 task3 task4 task5 task6

clean:
	rm task1 task2 task3 task4 task5 task6

task1: 
	$(CC) $(COPS) -o task1 task1.c

task2:
	$(CC) $(COPS) -o task2 task2.c

task3:        
	$(CC) $(COPS) -o task3 task3.c

task4:        
	$(CC) $(COPS) -o task4 task4.c

task5:        
	$(CC) $(COPS) -o task5 task5.c

task6:        
	$(CC) $(COPS) -o task6 task6.c