CC = gcc
C++ = g++
COPS = -Wall

make: task1 task2 task3 task4

clean:
	rm task1 task2 task3

task1:
	$(C++) $(COPS) -o task1 ex4task1.cpp

task2:
	$(C++) $(COPS) -o task2 ex4task2.cpp

task3:
	$(CC) $(COPS) -g -o task3 ex4task3.c

task4:
	$(C++) $(COPS) -o task4 ex4task4.cpp