CC = gcc
COPS = -Wall

make: task1 task2 task3

clean:
	rm task1 task2 task3

task1:
	$(CC) $(COPS) -o task1 task1.c

task2:
	$(CC) $(COPS) -o task2 task2.c

task3:
	$(CC) $(COPS) -g -o task3 ex3bonus.c