C++ = g++
COPS = -Wall -std=c++11

make: task1 task2 task3

clean:
	rm task1 task2 task3

cleanwin:
	del *.exe *.o

task1:
	$(C++) $(COPS) -o task1 mytime.cpp timetest.cpp 

task2: 
	$(C++) $(COPS) -o task2 secarr.cpp secarrtest.cpp

task3:
	$(C++) $(COPS) -o task3 task3.cpp